# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2024 Oplus. All rights reserved.

LINUXINCLUDE += -I$(srctree)/
obj-$(CONFIG_OPLUS_FEATURE_IO_MONITOR) += oplus_io_monitor.o
oplus_io_monitor-y := io_monitor.o
